global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'java-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'backend:6969' ]

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

