image: gradle:8.7-jdk21-alpine

stages:
  - build
  - test
  - package
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"
  DOCKER_TLS_CERTDIR: "/certs"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .gradle
    - build/libs

build-app:
  stage: build
  script:
    - gradle clean assemble -x test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

run-tests:
  stage: test
  script:
    - gradle test
  needs: ["build-app"]

docker-build:
  stage: package
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  needs:
    - job: build-app
      artifacts: true
  script:
    - MAIN_JAR=$(ls build/libs/*.jar | grep -v plain | head -1)
    - cp "$MAIN_JAR" application.jar
    - docker build --pull
      --build-arg JAVA_VERSION=21
      -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master"

deploy-develop:
  stage: deploy
  image: alpine:3.18
  before_script:
    - apk add --no-cache openssh-client sshpass docker-cli
  script:
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      docker pull $DOCKER_IMAGE &&
      docker stop vboost-back-dev || true;
      docker rm vboost-back-dev || true;
      echo \"USERNAME_DB=$DEV_DB_USER\" > .env &&
      echo \"PASSWORD_DB=$DEV_DB_PASSWORD\" >> .env &&
      echo \"JWT_SECRET_KEY=$DEV_JWT_SECRET\" >> .env &&
      echo \"FRONTEND_ORIGIN=$DEV_FRONTEND_HOST\" >> .env &&
      echo \"PASSWORD_MAIL=$DEV_PASSWORD_MAIL\" >> .env &&
      echo \"USERNAME_MAIL=$DEV_USERNAME_MAIL\" >> .env &&
      echo \"URL_DB=jdbc:postgresql://$DEV_DB_HOST:$DEV_DB_PORT/$DEV_DB_NAME\" >> .env &&
      echo \"JAVA_OPTS=-Xmx512m -Dspring.profiles.active=dev\" >> .env &&
      docker run -d --name vboost-back-dev -p 6969:6969 --env-file .env $DOCKER_IMAGE
      "
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  needs: ["docker-build"]

deploy-prod:
  stage: deploy
  image: alpine:3.18
  before_script:
    - apk add --no-cache openssh-client sshpass docker-cli
  script:
    - sshpass -p "$PROD_SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $PROD_SSH_USER@$PROD_SSH_HOST "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      docker pull $DOCKER_IMAGE &&
      docker stop vboosting-backend-prod || true;
      docker rm vboosting-backend-prod || true;
      echo \"USERNAME_DB=$PROD_DB_USER\" > .env &&
      echo \"PASSWORD_DB=$PROD_DB_PASSWORD\" >> .env &&
      echo \"JWT_SECRET_KEY=$PROD_JWT_SECRET\" >> .env &&
      echo \"FRONTEND_ORIGIN=$PROD_FRONTEND_HOST\" >> .env &&
      echo \"PASSWORD_MAIL=$PROD_PASSWORD_MAIL\" >> .env &&
      echo \"USERNAME_MAIL=$PROD_USERNAME_MAIL\" >> .env &&
      echo \"URL_DB=jdbc:postgresql://$PROD_DB_HOST:$PROD_DB_PORT/$PROD_DB_NAME\" >> .env &&
      echo \"JAVA_OPTS=-Xmx512m -Dspring.profiles.active=prod\" >> .env &&
      docker run -d --name vboost-back-prod -p 6969:6969 --env-file .env $DOCKER_IMAGE
      && rm .env
      "
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  needs: ["docker-build"]