ALTER TABLE game ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE game ALTER COLUMN is_active SET DEFAULT TRUE;

ALTER TABLE offers ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE offers ALTER COLUMN is_active SET DEFAULT TRUE;