CREATE TABLE IF NOT EXISTS games_categories
(
    id        INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "name"    VARCHAR(255)                                                                                                             NOT NULL,
    game_id   UUID                                                                                                                     NULL,
    parent_id INT8                                                                                                                     NULL,
    CONSTRAINT games_categories_pkey PRIMARY KEY (id),
    CONSTRAINT fk_games_categories_game FOREIGN KEY (game_id) REFERENCES game (id),
    CONSTRAINT fk_games_categories_parent FOREIGN KEY (parent_id) REFERENCES games_categories (id)
);
